# Generated by Django 5.2.7 on 2025-10-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('email', models.EmailField(help_text='Your email', max_length=254)),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ Excellent'), (4, '⭐⭐⭐⭐ Very Good'), (3, '⭐⭐⭐ Good'), (2, '⭐⭐ Fair'), (1, '⭐ Poor')])),
                ('comment', models.TextField(help_text='Share your experience...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, help_text='Approved for display')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='places.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
